""" little_change_type_inside_table and add field br_date

Revision ID: 52a53283483c
Revises: a0f26c13025d
Create Date: 2024-04-30 13:36:37.026334

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52a53283483c'
down_revision: Union[str, None] = 'a0f26c13025d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_meta', sa.Column('br_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_meta', 'br_date')
    # ### end Alembic commands ###
