"""add foreign key

Revision ID: 9f1f881c86f3
Revises: 52a53283483c
Create Date: 2024-04-30 14:55:10.712054

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f1f881c86f3"
down_revision: Union[str, None] = "52a53283483c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_meta", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "users_meta", ["user_id"])
    op.create_foreign_key(None, "users_meta", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_meta", type_="foreignkey")
    op.drop_constraint(None, "users_meta", type_="unique")
    op.drop_column("users_meta", "user_id")
    # ### end Alembic commands ###
