"""change architecture UserMeta and UserModel models

Revision ID: a1dd05f1cfe3
Revises: 867a53a3618c
Create Date: 2024-05-20 13:23:36.593160

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1dd05f1cfe3'
down_revision: Union[str, None] = '867a53a3618c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_token'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_constraint('users_meta_email_key', 'users_meta', type_='unique')
    op.drop_constraint('users_meta_phone_key', 'users_meta', type_='unique')
    op.drop_column('users_meta', 'fname')
    op.drop_column('users_meta', 'avatar')
    op.drop_column('users_meta', 'email')
    op.drop_column('users_meta', 'phone')
    op.drop_column('users_meta', 'lname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_meta', sa.Column('lname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_meta', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_meta', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_meta', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_meta', sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_meta_phone_key', 'users_meta', ['phone'])
    op.create_unique_constraint('users_meta_email_key', 'users_meta', ['email'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'email')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
