"""Create phone verify and user verify table

Revision ID: a684b08af721
Revises: c624d9ac8d78
Create Date: 2024-04-23 14:40:27.115786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684b08af721'
down_revision: Union[str, None] = 'c624d9ac8d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_session',
    sa.Column('id', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('verify_key', sa.Numeric(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_with_email.user_id'], name='fk_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones_session',
    sa.Column('id', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('verify_key', sa.Numeric(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_with_phone.user_id'], name='fk_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users_with_email', sa.Column('is_verify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_with_email', 'is_verify')
    op.drop_table('phones_session')
    op.drop_table('emails_session')
    # ### end Alembic commands ###
